#!/usr/bin/env bash

# Author: Zhang Huangbin (zhb _at_ iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# For SpamAssassin.

export SA_CONF_DIR='/etc/mail/spamassassin'
export SA_RULES_DIR='/usr/share/spamassassin'
export BIN_SA_UPDATE='sa-update'
export BIN_SA_COMPILE='sa-compile'

if [ X"${DISTRO}" == X'FREEBSD' ]; then
    export SA_CONF_DIR='/usr/local/etc/mail/spamassassin'
    export SA_RULES_DIR='/usr/local/share/spamassassin'
    export BIN_SA_UPDATE='/usr/local/bin/sa-update'
    export BIN_SA_COMPILE='/usr/local/bin/sa-compile'
fi

export SA_INIT_PRE="${SA_CONF_DIR}/init.pre"
export SA_LOCAL_CF="${SA_CONF_DIR}/local.cf"
export SA_PLUGIN_RAZOR_CONF="${SA_CONF_DIR}/razor.conf"
