#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb _at_ iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# Awstats homepage: http://awstats.sf.net/

# Variables for awstats and related.

export AWSTATS_HTTPD_CONF="${HTTPD_CONF_DIR}/awstats.conf"
export AWSTATS_CONF_DIR='/etc/awstats'
export AWSTATS_CONF_WEB="${AWSTATS_CONF_DIR}/awstats.web.conf"
export AWSTATS_CONF_MAIL="${AWSTATS_CONF_DIR}/awstats.smtp.conf"

# htpasswd file used for http basic auth
export AWSTATS_HTTPD_AUTH_FILE="${HTTPD_CONF_ROOT}/awstats.users"

# Required for setup with Nginx
export AWSTATS_CMD_BUILDSTATICPAGE='/usr/share/awstats/tools/awstats_buildstaticpages.pl'
export AWSTATS_STATIC_PAGES_DIR="${HTTPD_SERVERROOT}/awstats-statistics"

# Config files.
if [ X"${DISTRO}" == X'RHEL' ]; then
    export AWSTATS_CONF_SAMPLE="${AWSTATS_CONF_DIR}/awstats.localhost.localdomain.conf"
    export AWSTATS_HTTPD_ROOT="/usr/share/awstats/wwwroot"
    export AWSTATS_CGI_DIR="${AWSTATS_HTTPD_ROOT}/cgi-bin"
    export AWSTATS_ICON_DIR="${AWSTATS_HTTPD_ROOT}/icon"
    export AWSTATS_CSS_DIR="${AWSTATS_HTTPD_ROOT}/css"
    export AWSTATS_JS_DIR="${AWSTATS_HTTPD_ROOT}/js"

elif [ X"${DISTRO}" == X'UBUNTU' -o X"${DISTRO}" == X'DEBIAN' ]; then
    export AWSTATS_CONF_SAMPLE="${AWSTATS_CONF_DIR}/awstats.conf"
    export AWSTATS_HTTPD_ROOT="/usr/share/awstats"
    export AWSTATS_ICON_DIR="${AWSTATS_HTTPD_ROOT}/icon"
    export AWSTATS_CSS_DIR="${AWSTATS_HTTPD_ROOT}/css"
    export AWSTATS_JS_DIR="${AWSTATS_HTTPD_ROOT}/js"

    # This path will be changed in 'functions/awstats.sh'.
    export AWSTATS_CGI_DIR="/usr/lib/cgi-bin"

elif [ X"${DISTRO}" == X'FREEBSD' ]; then
    export AWSTATS_HTTPD_ROOT="${HTTPD_SERVERROOT}/awstats"
    export AWSTATS_ICON_DIR="${AWSTATS_HTTPD_ROOT}/icon"
    export AWSTATS_CSS_DIR="${AWSTATS_HTTPD_ROOT}/css"
    export AWSTATS_JS_DIR="${AWSTATS_HTTPD_ROOT}/js"
    export AWSTATS_CONF_DIR="${AWSTATS_HTTPD_ROOT}/cgi-bin"
    export AWSTATS_CONF_SAMPLE="${AWSTATS_CONF_DIR}/awstats.model.conf"
    export AWSTATS_CGI_DIR="${AWSTATS_CONF_DIR}"

    # Override default settings.
    export AWSTATS_CONF_WEB="${AWSTATS_CONF_DIR}/awstats.web.conf"
    export AWSTATS_CONF_MAIL="${AWSTATS_CONF_DIR}/awstats.smtp.conf"

    # Required for setup with Nginx
    export AWSTATS_CMD_BUILDSTATICPAGE="${AWSTATS_HTTPD_ROOT}/tools/awstats_buildstaticpages.pl"

elif [ X"${DISTRO}" == X'OPENBSD' ]; then
    export AWSTATS_HTTPD_ROOT="${HTTPD_SERVERROOT}/awstats/wwwroot"
    export AWSTATS_ICON_DIR="${AWSTATS_HTTPD_ROOT}/icon"
    export AWSTATS_CSS_DIR="${AWSTATS_HTTPD_ROOT}/css"
    export AWSTATS_JS_DIR="${AWSTATS_HTTPD_ROOT}/js"
    export AWSTATS_CGI_DIR="${AWSTATS_HTTPD_ROOT}/cgi-bin"
    export AWSTATS_CONF_DIR="${AWSTATS_CGI_DIR}"
    export AWSTATS_CONF_SAMPLE="${AWSTATS_CONF_DIR}/awstats.model.conf"

    # Override default settings.
    export AWSTATS_CONF_WEB="${AWSTATS_CONF_DIR}/awstats.web.conf"
    export AWSTATS_CONF_MAIL="${AWSTATS_CONF_DIR}/awstats.smtp.conf"

    # Required for setup with Nginx
    export AWSTATS_CMD_BUILDSTATICPAGE='/var/www/awstats/tools/awstats_buildstaticpages.pl'
    export AWSTATS_STATIC_PAGES_DIR='/var/www/awstats/statistics'
fi

# Path to awstats.pl
export AWSTATS_CMD_AWSTATS_PL="${AWSTATS_CGI_DIR}/awstats.pl"

# Default language.
#   English:        en
#   Simp Chinese:   cn
#   Trad Chinese:   tw
export AWSTATS_LANGUAGE='en'
