#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb _at_ iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

export CLAMAV_USER='clamav'
export CLAMAV_GROUP='clamav'
export CLAMAV_CLAMD_RC_SCRIPT_NAME='clamd'
export CLAMAV_FRESHCLAMD_RC_SCRIPT_NAME='freshclamd'

export CLAMD_CONF='/etc/clamd.conf'
export CLAMD_LOGFILE='/var/log/clamav/clamd.log'
# CLAMD_BIND_HOST is configured in conf/global
export CLAMD_LOCAL_SOCKET='/tmp/clamd.socket'   # Used to override default setting.

export FRESHCLAM_CONF='/etc/freshclam.conf'
export FRESHCLAM_LOGFILE='/var/log/clamav/freshclam.log'
export FRESHCLAM_PID_FILE='/var/run/clamav/freshclam.pid'

# Clamav.
if [ X"${DISTRO}" == X"RHEL" ]; then
    # Freshclam.
    export FRESHCLAM_INIT_FILE_SAMPLE="${SAMPLE_DIR}/freshclam.init"

elif [ X"${DISTRO}" == X"SUSE" ]; then
    export CLAMAV_FRESHCLAMD_RC_SCRIPT_NAME='freshclam'

elif [ X"${DISTRO}" == X"DEBIAN" -o X"${DISTRO}" == X"UBUNTU" ]; then
    export CLAMAV_CLAMD_RC_SCRIPT_NAME='clamav-daemon'
    export CLAMAV_FRESHCLAMD_RC_SCRIPT_NAME='clamav-freshclam'

    export CLAMD_CONF='/etc/clamav/clamd.conf'
    export FRESHCLAM_CONF='/etc/clamav/freshclam.conf'

elif [ X"${DISTRO}" == X"FREEBSD" ]; then
    export CLAMD_CONF='/usr/local/etc/clamd.conf'
    export FRESHCLAM_CONF='/usr/local/etc/freshclam.conf'

elif [ X"${DISTRO}" == X'OPENBSD' ]; then
    export CLAMAV_USER='_clamav'
    export CLAMAV_GROUP='_clamav'
    export CLAMAV_FRESHCLAMD_RC_SCRIPT_NAME='freshclam'

    export FRESHCLAM_PID_FILE='/var/run/freshclam.pid'
fi

# Clamd local socket.
if [ X"${DISTRO}" == X"GENTOO" \
    -o X"${DISTRO}" == X"FREEBSD" \
    ]; then
    export CLAMD_LOCAL_SOCKET='/var/run/clamav/clamd.sock'
fi
