#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb(at)iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# ------------------------------------------------
# Policyd-2.x (code name: cluebringer).
# ------------------------------------------------

export CLUEBRINGER_BINDHOST='127.0.0.1'
export CLUEBRINGER_BINDPORT='10031'

# Database.
export CLUEBRINGER_DB_NAME='cluebringer'
export CLUEBRINGER_DB_USER='cluebringer'
export CLUEBRINGER_DB_PASSWD="$(${RANDOM_STRING})"

export CLUEBRINGER_USER='cluebringer'
export CLUEBRINGER_GROUP='cluebringer'
export CLUEBRINGER_USER_HOME='/etc/cluebringer'

#
# Syslog setting.
#
export CLUEBRINGER_SEPERATE_LOG='NO'    # 'YES' or 'NO'

# Default syslog facility is 'LOG_MAIL|LOG_INFO'
export CLUEBRINGER_SYSLOG_FACILITY='LOG_MAIL|LOG_INFO'
export CLUEBRINGER_LOGROTATE_FILE='/etc/logrotate.d/policyd'
export CLUEBRINGER_LOG_FILE='/var/log/cbpolicyd.log'

if [ X"${DISTRO}" == X"RHEL" ]; then
    export PKG_CLUEBRINGER='policyd'
    export CLUEBRINGER_CONF='/etc/policyd.conf'
    export CLUEBRINGER_INIT_SCRIPT="${DIR_RC_SCRIPTS}/policyd"
    export CLUEBRINGER_PID_FILE='/var/run/cluebringer/cbpolicyd.pid'

    # Path of policyd-clean
    export CLUEBRINGER_CLEANUP_BIN='/usr/sbin/policyd-cleanup'

elif [ X"${DISTRO}" == X"SUSE" ]; then
    export PKG_CLUEBRINGER='policyd'
    export CLUEBRINGER_CONF='/etc/cluebringer/cluebringer.conf'
    export CLUEBRINGER_INIT_SCRIPT="${DIR_RC_SCRIPTS}/policyd"
    export CLUEBRINGER_PID_FILE='var/run/cluebringer/cbpolicyd.pid'

    # Path of policyd-clean
    export CLUEBRINGER_CLEANUP_BIN='/usr/lib/policyd/cleanup'

    # Override default setting.
    export CLUEBRINGER_USER_HOME='/var/lib/empty'

elif [ X"${DISTRO}" == X"DEBIAN" -o X"${DISTRO}" == X"UBUNTU" ]; then
    export PKG_CLUEBRINGER='postfix-cluebringer'
    export CLUEBRINGER_CONF='/etc/cluebringer/cluebringer.conf'
    export CLUEBRINGER_INIT_SCRIPT="${DIR_RC_SCRIPTS}/postfix-policyd"
    export CLUEBRINGER_PID_FILE='var/run/cluebringer/cbpolicyd.pid'

    # Path of policyd-clean
    export CLUEBRINGER_CLEANUP_BIN='/usr/lib/postfix-policyd/cleanup'

elif [ X"${DISTRO}" == X"FREEBSD" ]; then
    export PKG_CLUEBRINGER='postfix-policyd-sf'
    export CLUEBRINGER_CONF='/usr/local/etc/postfix-policyd-sf.conf'
    export CLUEBRINGER_INIT_SCRIPT="${DIR_RC_SCRIPTS}/policyd"
    export CLUEBRINGER_PID_FILE='var/run/cluebringer/cbpolicyd.pid'

    # Path of policyd-clean
    export CLUEBRINGER_CLEANUP_BIN='/usr/local/sbin/postfix-policyd-sf-cleanup'

else
    :
fi

export BACKUP_DATABASES="${BACKUP_DATABASES} ${CLUEBRINGER_DB_NAME}"
