#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb _at_ iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# ------------------------------------------------
# Policyd-2.x (code name: cluebringer).
# ------------------------------------------------

# CLUEBRINGER_BIND_HOST is configured in conf/global.
export CLUEBRINGER_BIND_PORT='10031'
export CLUEBRINGER_RC_SCRIPT_NAME='cluebringer'

# Path to cbpadmin.
# cbpadmin is responsible for deleting old entries from the database.
export CLUEBRINGER_BIN_CBPADMIN='/usr/sbin/cbpadmin'

# Database.
export CLUEBRINGER_DB_NAME='cluebringer'
export CLUEBRINGER_DB_USER='cluebringer'

export CLUEBRINGER_USER='cluebringer'
export CLUEBRINGER_GROUP='cluebringer'
export CLUEBRINGER_USER_HOME='/etc/cluebringer'
export CLUEBRINGER_HTTPD_CONF="${HTTPD_CONF_DIR}/cluebringer.conf"

#
# Syslog setting.
#
export CLUEBRINGER_SEPARATE_LOG='YES'    # 'YES' or 'NO'

# Default syslog facility is 'LOG_MAIL|LOG_INFO'
export CLUEBRINGER_SYSLOG_FACILITY='LOG_MAIL|LOG_INFO'
export CLUEBRINGER_LOGROTATE_FILE="${LOGROTATE_DIR}/policyd"
export CLUEBRINGER_LOG_FILE='/var/log/cbpolicyd.log'

if [ X"${DISTRO}" == X"RHEL" ]; then
    export PKG_CLUEBRINGER='cluebringer'
    export CLUEBRINGER_RC_SCRIPT_NAME='cbpolicyd'
    export CLUEBRINGER_CONF='/etc/policyd/cluebringer.conf'
    export CLUEBRINGER_WEBUI_CONF="/etc/policyd/webui.conf"
    export CLUEBRINGER_PID_FILE='/var/run/cbpolicyd.pid'
    export CLUEBRINGER_HTTPD_ROOT='/usr/share/cluebringer/webui'

    # Override default setting.
    export CLUEBRINGER_USER_HOME='/home/cbpolicyd'

elif [ X"${DISTRO}" == X"DEBIAN" -o X"${DISTRO}" == X"UBUNTU" ]; then
    export PKG_CLUEBRINGER='postfix-cluebringer'
    export CLUEBRINGER_CONF='/etc/cluebringer/cluebringer.conf'
    export CLUEBRINGER_WEBUI_CONF="/etc/cluebringer/cluebringer-webui.conf"
    export CLUEBRINGER_RC_SCRIPT_NAME='postfix-cluebringer'
    export CLUEBRINGER_PID_FILE='/var/run/cluebringer/cbpolicyd.pid'
    export CLUEBRINGER_HTTPD_ROOT='/usr/share/postfix-cluebringer-webui/webui'

    export CLUEBRINGER_HTTPD_CONF="${HTTPD_CONF_DIR}/zcluebringer.conf"

elif [ X"${DISTRO}" == X"FREEBSD" ]; then
    export CLUEBRINGER_USER='policyd'
    export CLUEBRINGER_GROUP='policyd'

    export CLUEBRINGER_BIN_CBPADMIN='/usr/local/bin/cbpadmin'

    export PKG_CLUEBRINGER='policyd2'
    export CLUEBRINGER_CONF='/usr/local/etc/cluebringer.conf'
    export CLUEBRINGER_WEBUI_CONF="${HTTPD_CONF_DIR}/cluebringer.conf"
    export CLUEBRINGER_PID_FILE='/var/run/cbpolicyd.pid'
    export CLUEBRINGER_HTTPD_ROOT='/usr/share/cluebringer/webui'

fi

export CLUEBRINGER_RC_SCRIPT="${DIR_RC_SCRIPTS}/${CLUEBRINGER_RC_SCRIPT_NAME}"

export MYSQL_BACKUP_DATABASES="${MYSQL_BACKUP_DATABASES} ${CLUEBRINGER_DB_NAME}"
export PGSQL_BACKUP_DATABASES="${PGSQL_BACKUP_DATABASES} ${CLUEBRINGER_DB_NAME}"
