#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb _at_ iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

export IREDAPD_VERSION='2.7'
export SYS_USER_IREDAPD='iredapd'
export SYS_GROUP_IREDAPD='iredapd'

export IREDAPD_TARBALL="iRedAPD-${IREDAPD_VERSION}.tar.bz2"
export IREDAPD_PARENT_DIR='/opt'
export IREDAPD_ROOT_DIR="${IREDAPD_PARENT_DIR}/iRedAPD-${IREDAPD_VERSION}"
export IREDAPD_ROOT_DIR_SYMBOL_LINK="${IREDAPD_PARENT_DIR}/iredapd"
export IREDAPD_CONF="${IREDAPD_ROOT_DIR_SYMBOL_LINK}/settings.py"

# IREDAPD_BIND_HOST is configured in conf/global
export IREDAPD_LISTEN_PORT='7777'
export IREDAPD_SRS_FORWARD_PORT='7778'
export IREDAPD_SRS_REVERSE_PORT='7779'

export IREDAPD_PID_FILE='/var/run/iredapd.pid'
export IREDAPD_LOG_DIR='/var/log/iredapd'
export IREDAPD_LOG_FILE="${IREDAPD_LOG_DIR}/iredapd.log"
export IREDAPD_LOGROTATE_FILE="${LOGROTATE_DIR}/iredapd"

# Database
# IREDAPD_DB_PASSWD is generated in dialog/optional_components.sh.
export IREDAPD_DB_NAME='iredapd'
export IREDAPD_DB_USER='iredapd'
