#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb _at_ iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

export IREDADMIN_VERSION='beta'
export IREDADMIN_TARBALL="iRedAdmin-${IREDADMIN_VERSION}.tar.bz2"
export IREDADMIN_HTTPD_ROOT="${HTTPD_SERVERROOT}/iRedAdmin-${IREDADMIN_VERSION}"
export IREDADMIN_HTTPD_ROOT_SYMBOL_LINK="${HTTPD_SERVERROOT}/iredadmin"
export IREDADMIN_HTTPD_CONF="${HTTPD_CONF_DIR}/iredadmin.conf"

# Run iRedAdmin with Apache + mod_wsgi, but as a low privilege user/group.
export IREDADMIN_HOME_DIR='/home/iredadmin'
export IREDADMIN_USER_NAME='iredadmin'
export IREDADMIN_GROUP_NAME="${IREDADMIN_USER_NAME}"

# MySQL database name, username and password.
export IREDADMIN_DB_NAME="${IREDADMIN_USER_NAME}"
export IREDADMIN_DB_USER="${IREDADMIN_USER_NAME}"

export SQL_BACKUP_DATABASES="${SQL_BACKUP_DATABASES} ${IREDADMIN_DB_NAME}"

# Configure file for uwsgi
export IREDADMIN_UWSGI_CONF="${UWSGI_CONF_DIR}/iredadmin.ini"
