#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb(at)iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# Variables for managesieve service.
export MANAGESIEVE_BINDADDR='127.0.0.1'
export MANAGESIEVE_PORT='2000'

# New Linux releases use port 4190.
# RHEL 6.
if [ X"${DISTRO}" == X"RHEL" ]; then
    [ X"${DISTRO_VERSION}" == X"6" ] && export MANAGESIEVE_PORT='4190'
elif [ X"${DISTRO}" == X"GENTOO" ]; then
    export MANAGESIEVE_PORT='4190'
fi

# Debian 6 (squeeze), Ubuntu 11.10 (oneiric).
if [ X"${DISTRO_CODENAME}" == X"squeeze" \
    -o X"${DISTRO_CODENAME}" == X"oneiric" \
    ]; then
    export MANAGESIEVE_PORT='4190'
fi
