#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb _at_ iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# Variables for MySQL database server and related.
# MYSQL_SERVER_ADDRESS and MYSQL_SERVER_PORT are defined in conf/global.
# SQL_SERVER_ADDRESS and SQL_SERVER_PORT are defined in dialog/config_via_dialog.sh.

export MYSQL_MY_CNF='/etc/my.cnf'
export MYSQL_MY_CNF_SAMPLE="${SAMPLE_DIR}/mysql/my.cnf"

export MYSQL_RC_SCRIPT_NAME='mysql'

# MySQL config file.
if [ X"${DISTRO}" == X'RHEL' ]; then
    if [ X"${DISTRO_VERSION}" == X'6' ]; then
        export MYSQL_RC_SCRIPT_NAME='mysqld'
    else
        export MYSQL_RC_SCRIPT_NAME='mariadb'
    fi

elif [ X"${DISTRO}" == X'UBUNTU' -o X"${DISTRO}" == X'DEBIAN' ]; then
    export MYSQL_MY_CNF='/etc/mysql/my.cnf'

    if [ X"${DISTRO_CODENAME}" == X'xenial' ]; then
        if [ X"${BACKEND_ORIG}" == X'MYSQL' ]; then
            export MYSQL_MY_CNF='/etc/mysql/mysql.conf.d/mysqld.cnf'
        elif [ X"${BACKEND_ORIG}" == X'MARIADB' ]; then
            export MYSQL_MY_CNF='/etc/mysql/mariadb.conf.d/mysqld.cnf'
        fi
    fi
elif [ X"${DISTRO}" == X'FREEBSD' ]; then
    export MYSQL_RC_SCRIPT_NAME='mysql-server'
    export MYSQL_MY_CNF='/usr/local/etc/mysql/my.cnf'
    export MYSQL_MY_CNF_SAMPLE='/usr/local/share/mysql/my-default.cnf'

elif [ X"${DISTRO}" == X'OPENBSD' ]; then
    export MYSQL_RC_SCRIPT_NAME='mysqld'
fi

export MYSQLD_RC_SCRIPT="${DIR_RC_SCRIPTS}/${MYSQL_RC_SCRIPT_NAME}"
export MYSQL_INIT_SQL="${RUNTIME_DIR}/mysql_init.sql"
export MYSQL_VMAIL_SQL="${RUNTIME_DIR}/mysql_vmail.sql"

# SQL structure of MySQL vmail database.
export MYSQL_VMAIL_STRUCTURE_SAMPLE="${SAMPLE_DIR}/iredmail/iredmail.mysql"

if [ X"${BACKEND}" == X'MYSQL' -o X"${BACKEND}" == X'OPENLDAP' ]; then
    export SQL_BACKUP_DATABASES="${SQL_BACKUP_DATABASES} mysql"
fi

# A temporary file which stores MySQL root password to avoid MySQL client
# warning: "Using a password on the command line interface can be insecure."
# File will be removed automatically after iRedMail installation.
export MYSQL_DEFAULTS_FILE_ROOT='/root/.my.cnf'
export MYSQL_CLIENT_ROOT="mysql --defaults-file=${MYSQL_DEFAULTS_FILE_ROOT}"

# Hostname or IP address used in MySQL GRANT command (allow remote access from
# this hostname/IP).
# Usually it's 'localhost', but not in FreeBSD Jail (use ${LOCAL_ADDRESS} or
# hostname of Jail instead).
if [ X"${LOCAL_ADDRESS}" == X'127.0.0.1' ]; then
    # Pre-define MYSQL_GRANT_HOST while running iRedMail to use a remote MySQL
    # server. For example:
    # MYSQL_GRANT_HOST='192.168.1.2' bash iRedMail.sh
    export MYSQL_GRANT_HOST="${MYSQL_GRANT_HOST:=localhost}"
else
    export MYSQL_GRANT_HOST="${LOCAL_ADDRESS}"
fi
