#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb _at_ iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# netdata: https://my-netdata.io
export NETDATA_PARENT_DIR='/opt'
export NETDATA_ROOT_DIR="${NETDATA_PARENT_DIR}/netdata"
export NETDATA_CONF_DIR="${NETDATA_ROOT_DIR}/etc/netdata"

export NETDATA_PORT='19999'

# Main config files.
export NETDATA_CONF="${NETDATA_CONF_DIR}/netdata.conf"
export NETDATA_STREAM_CONF="${NETDATA_CONF_DIR}/stream.conf"

# .my.cnf used to access MySQL db.
export NETDATA_DOT_MY_CNF="${NETDATA_CONF_DIR}/my.cnf"

# Install stable release.
export NETDATA_VERSION='1.9.0'
export NETDATA_DOWNLOAD_URL="https://github.com/firehol/netdata/releases/download/v${NETDATA_VERSION}/netdata-latest.gz.run"

# Modular config files.
export NETDATA_CONF_HEALTH_ALARM_NOTIFY="${NETDATA_CONF_DIR}/health_alarm_notify.conf"

# Plugin config files.
export NETDATA_CONF_PLUGIN_FAIL2BAN="${NETDATA_CONF_DIR}/python.d/fail2ban.conf"
export NETDATA_CONF_PLUGIN_MYSQL="${NETDATA_CONF_DIR}/python.d/mysql.conf"
export NETDATA_CONF_PLUGIN_PHPFPM="${NETDATA_CONF_DIR}/python.d/phpfpm.conf"
export NETDATA_CONF_PLUGIN_NGINX="${NETDATA_CONF_DIR}/python.d/nginx.conf"

# Log directories and files
export NETDATA_LOG_DIR='/var/log/netdata'
export NETDATA_LOG_ACCESSLOG="${NETDATA_LOG_DIR}/access.log"
export NETDATA_LOG_ERRORLOG="${NETDATA_LOG_DIR}/error.log"
export NETDATA_LOG_DEBUGLOG="${NETDATA_LOG_DIR}/debug.log"
