#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb(at)iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

if [ X"${DISTRO_CODENAME}" == X"oneiric" \
    -o X"${DISTRO_CODENAME}" == X"precise" \
    ]; then
    # Use Policyd-2.x (cluebringer).
    export USE_CLUEBRINGER='YES'
    export USE_POLICYD='NO'

    . ${CONF_DIR}/cluebringer
else
    # Use Policyd-1.x.
    export USE_CLUEBRINGER='NO'
    export USE_POLICYD='YES'

    . ${CONF_DIR}/policyd
fi
