#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb _at_ iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# Use policyd-1.8 by default
export USE_CLUEBRINGER='NO'
export USE_POLICYD='YES'

# Use Policyd-2.x (cluebringer).
if [ X"${DISTRO}" == X'RHEL' -o X"${DISTRO}" == X'SUSE' ]; then
    if [ X"${BACKEND}" == X'PGSQL' ]; then
        export USE_CLUEBRINGER='YES'
        export USE_POLICYD='NO'
    fi
elif [ X"${DISTRO}" == X'DEBIAN' ]; then
    if [ X"${DISTRO_CODENAME}" == X'wheezy' ]; then
        export USE_CLUEBRINGER='YES'
        export USE_POLICYD='NO'
    fi

elif [ X"${DISTRO}" == X'UBUNTU' ]; then
    export USE_CLUEBRINGER='YES'
    export USE_POLICYD='NO'
elif [ X"${DISTRO}" == X'FREEBSD' ]; then
    if [ X"${BACKEND}" == X'PGSQL' ]; then
        export USE_CLUEBRINGER='YES'
        export USE_POLICYD='NO'
    fi
elif [ X"${DISTRO}" == X'OPENBSD' ]; then
    export USE_CLUEBRINGER='NO'
    export USE_POLICYD='NO'
    export USE_SPAMD='YES'
fi

if [ X"${USE_POLICYD}" == X'YES' ]; then
    . ${CONF_DIR}/policyd
fi

if [ X"${USE_CLUEBRINGER}" == X'YES' ]; then
    . ${CONF_DIR}/cluebringer
fi
