#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb _at_ iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# ------------------------------------------------
# Policyd.
# ------------------------------------------------

# POLICYD_BIND_HOST is configured in conf/global
export POLICYD_BIND_PORT='10031' # Default value in policyd.conf.

export POLICYD_RC_SCRIPT_NAME='policyd'
export POLICYD_DB_PASSWD="$(${RANDOM_STRING})"

export POLICYD_USER='policyd'
export POLICYD_GROUP='policyd'
export POLICYD_USER_HOME='/home/policyd'

#
# Another policyd instance for recipient throttle feature only.
#
export POLICYD_THROTTLE_PIDFILE='/var/run/policyd_throttle.pid'

export POLICYD_THROTTLE_BIND_HOST="${POLICYD_BIND_HOST}"
export POLICYD_THROTTLE_BIND_PORT='10032'

#
# Syslog setting.
#
export POLICYD_SEPERATE_LOG='NO'    # 'YES' or 'NO'

# Default syslog facility is 'LOG_MAIL|LOG_INFO'
export POLICYD_SYSLOG_FACILITY='LOG_MAIL|LOG_INFO'
export POLICYD_LOGFILE='/var/log/policyd.log'
export POLICYD_LOGROTATE_FILE='/etc/logrotate.d/policyd'

if [ X"${DISTRO}" == X"RHEL" ]; then
    export PKG_POLICYD='policyd'
    export POLICYD_CONF='/etc/policyd.conf'
    export POLICYD_THROTTLE_CONF='/etc/policyd_sender_throttle.conf'
    export POLICYD_THROTTLE_PIDFILE='/var/run/policyd_sender_throttle.pid'

    # Database.
    export POLICYD_DB_NAME='policyd'
    export POLICYD_DB_USER='policyd'

    # Path of policyd-clean
    export POLICYD_CLEANUP_BIN='/usr/sbin/policyd-cleanup'

elif [ X"${DISTRO}" == X"SUSE" ]; then
    export PKG_POLICYD='policyd'
    export POLICYD_CONF='/etc/policyd.conf'
    export POLICYD_THROTTLE_CONF='/etc/policyd_sender_throttle.conf'
    export POLICYD_THROTTLE_PIDFILE='/var/run/policyd_sender_throttle.pid'

    # Database.
    export POLICYD_DB_NAME='policyd'
    export POLICYD_DB_USER='policyd'

    # Path of policyd-clean
    export POLICYD_CLEANUP_BIN='/usr/lib/policyd/cleanup'

    # Override default setting.
    export POLICYD_USER_HOME='/var/lib/empty'

elif [ X"${DISTRO}" == X"DEBIAN" -o X"${DISTRO}" == X"UBUNTU" ]; then
    export PKG_POLICYD='postfix-policyd'
    export POLICYD_CONF='/etc/postfix-policyd.conf'
    export POLICYD_THROTTLE_CONF='/etc/postfix-policyd_throttle.conf'
    export POLICYD_RC_SCRIPT_NAME="postfix-policyd"

    # Database.
    export POLICYD_DB_NAME='postfixpolicyd'
    export POLICYD_DB_USER='postfix-policyd'

    # Path of policyd-clean
    export POLICYD_CLEANUP_BIN='/usr/lib/postfix-policyd/cleanup'

elif [ X"${DISTRO}" == X"GENTOO" ]; then
    export PKG_POLICYD='policyd'
    export POLICYD_CONF='/etc/policyd.conf'
    export POLICYD_THROTTLE_CONF='/etc/policyd_sender_throttle.conf'
    export POLICYD_THROTTLE_PIDFILE='/var/run/policyd_sender_throttle.pid'

    # Database.
    export POLICYD_DB_NAME='policyd'
    export POLICYD_DB_USER='policyd'

    # Path of policyd-clean
    export POLICYD_CLEANUP_BIN='/usr/sbin/policyd_cleanup'

elif [ X"${DISTRO}" == X"FREEBSD" ]; then
    export PKG_POLICYD='postfix-policyd-sf'
    export POLICYD_CONF='/usr/local/etc/postfix-policyd-sf.conf'
    export POLICYD_THROTTLE_CONF='/usr/local/etc/policyd_throttle.conf'

    # Database.
    export POLICYD_DB_NAME='policyd'
    export POLICYD_DB_USER='policyd'

    # Path of policyd-clean
    export POLICYD_CLEANUP_BIN='/usr/local/sbin/postfix-policyd-sf-cleanup'

else
    :
fi

export POLICYD_RC_SCRIPT="${DIR_RC_SCRIPTS}/${POLICYD_RC_SCRIPT_NAME}"
export MYSQL_BACKUP_DATABASES="${MYSQL_BACKUP_DATABASES} ${POLICYD_DB_NAME}"
