#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb(at)iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# Variables for PostgreSQL database server and related.

export PGSQL_SYS_USER='postgres'
export PGSQL_SYS_GROUP='postgres'
export PGSQL_ROOT_USER='postgres'
export PGSQL_INIT_SCRIPT="${DIR_RC_SCRIPTS}/postgresql"
export PGSQL_VMAIL_STRUCTURE_SAMPLE="${SAMPLE_DIR}/iredmail.pgsql"

if [ X"${DISTRO}" == X"UBUNTU" ]; then
    export PGSQL_SYS_USER='postgres'
    export PGSQL_SYS_GROUP='postgres'
fi

export BACKUP_PGSQL_DATABASES="${BACKUP_PGSQL_DATABASES}"
if [ X"${BACKEND}" == X"PGSQL" ]; then
    export BACKUP_PGSQL_DATABASES="${BACKUP_PGSQL_DATABASES} ${VMAIL_DB}"
fi
