#!/usr/bin/env bash

# Author:   Zhang Huangbin (zhb(at)iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# Variables for PostgreSQL database server and related.

export PGSQL_SYS_USER='postgres'
export PGSQL_SYS_GROUP='postgres'

export PGSQL_SERVER='localhost'
export PGSQL_ROOT_USER='postgres'

export PGSQL_SYS_USER_HOME='/var/lib/postgresql'
export PGSQL_DOT_PGPASS="${PGSQL_SYS_USER_HOME}/.pgpass"

export PGSQL_INIT_SCRIPT="${DIR_RC_SCRIPTS}/postgresql"
export PGSQL_VMAIL_STRUCTURE_SAMPLE="${SAMPLE_DIR}/iredmail.pgsql"
export PGSQL_INIT_SQL_SAMPLE="${CONF_DIR}/pgsql_init.pgsql"

export PGSQL_VERSION='9.1'
export PGSQL_CONF_DIR="/etc/postgresql/${PGSQL_VERSION}/main"
export PGSQL_CONF_POSTGRESQL="${PGSQL_CONF_DIR}/postgresql.conf"
export PGSQL_CONF_PG_HBA="${PGSQL_CONF_DIR}/pg_hba.conf"

export PGSQL_DATA_DIR="/var/lib/postgresql/${PGSQL_VERSION}/main"

# SSL cert/key
export PGSQL_SSL_CERT="${SSL_CERT_DIR}/iRedMail_CA_PostgreSQL.pem"
export PGSQL_SSL_KEY="${SSL_KEY_DIR}/iRedMail_PostgreSQL.key"

export PGSQL_BACKUP_DATABASES="${PGSQL_BACKUP_DATABASES}"
if [ X"${BACKEND}" == X"PGSQL" ]; then
    export PGSQL_BACKUP_DATABASES="${PGSQL_BACKUP_DATABASES} ${VMAIL_DB}"
fi
