#!/usr/bin/env bash

# Author: Zhang Huangbin (zhb _at_ iredmail.org)

#---------------------------------------------------------------------
# This file is part of iRedMail, which is an open source mail server
# solution for Red Hat(R) Enterprise Linux, CentOS, Debian and Ubuntu.
#
# iRedMail is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# iRedMail is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with iRedMail.  If not, see <http://www.gnu.org/licenses/>.
#---------------------------------------------------------------------

# ---------------------------------------
# RoundcubeMail. http://roundcube.net
# ---------------------------------------
export RCM_VERSION='1.1.2'
export RCM_TARBALL="roundcubemail-${RCM_VERSION}-complete.tar.gz"
export RCM_USE_SOURCE='YES'

if [ X"${DISTRO}" == X'FREEBSD' ]; then
    # Install via ports tree
    export RCM_USE_SOURCE='NO'
fi

if [ X"${RCM_USE_SOURCE}" == X'YES' ]; then
    export RCM_HTTPD_ROOT="${HTTPD_SERVERROOT}/roundcubemail-${RCM_VERSION}"
    export RCM_HTTPD_ROOT_SYMBOL_LINK="${HTTPD_SERVERROOT}/roundcubemail"
else
    if [ X"${DISTRO}" == X'FREEBSD' ]; then
        export RCM_HTTPD_ROOT="${HTTPD_SERVERROOT}/roundcube"
        export RCM_HTTPD_ROOT_SYMBOL_LINK="${RCM_HTTPD_ROOT}"
    fi
fi

export RCM_CONF_DIR="${RCM_HTTPD_ROOT}/config"

# Sample sieve filter template
export RCM_SIEVE_SAMPLE_FILE="${RCM_CONF_DIR}/dovecot.sieve"

# Syslog log file.
export RCM_LOGFILE="${MAILLOG}"

# Database setting.
export RCM_DB="roundcubemail"
export RCM_DB_USER="roundcube"

# this key is used to encrypt the users imap password which is stored
# in the session record (and the client cookie if remember password is enabled).
# please provide a string of exactly 24 chars.
export tmp_rcm_des_key="$(${RANDOM_STRING})"
export RCM_DES_KEY="$(echo ${tmp_rcm_des_key} | cut -c-24)"

# Backup database.
if [ X"${USE_RCM}" == X'YES' ]; then
    export MYSQL_BACKUP_DATABASES="${MYSQL_BACKUP_DATABASES} ${RCM_DB}"
    export PGSQL_BACKUP_DATABASES="${PGSQL_BACKUP_DATABASES} ${RCM_DB}"
fi
