ALTER TABLE mailbox ADD COLUMN IF NOT EXISTS "enablesogowebmail" INT2 NOT NULL DEFAULT 1;
ALTER TABLE mailbox ADD COLUMN IF NOT EXISTS "enablesogocalendar" INT2 NOT NULL DEFAULT 1;
ALTER TABLE mailbox ADD COLUMN IF NOT EXISTS "enablesogoactivesync" INT2 NOT NULL DEFAULT 1;
